databases:
  - name: dpg-ch4cl1e4dad97s24n5tg-a
    databaseName: budget_database_n0ja
    user: budget_database_n0ja_user

services:
  - type: web
    name: dpg-ch4cl1e4dad97s24n5tg-a
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_database_n0ja
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
